# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             3003
url:              http://salesforcexytools.com
baseurl:          /lightning-ui
encoding:         UTF-8

# gems:
#   - jekyll-sitemap

# Custom vars
current_version:  1.0.0
repo:             https://github.com/exiahuang/lightning-ui
sass_repo:        https://github.com/exiahuang/lightning-ui

# download:
#   source:         https://github.com/twbs/bootstrap/archive/v3.4.0.zip
#   dist:           https://github.com/twbs/bootstrap/releases/download/v3.4.0/bootstrap-3.4.0-dist.zip
#   sass:           https://github.com/twbs/bootstrap-sass/archive/v3.4.0.tar.gz

# blog:             http://blog.getbootstrap.com
# expo:             http://expo.getbootstrap.com
# themes:           http://themes.getbootstrap.com
# jobs:             http://jobs.getbootstrap.com


